git:
  paging:
    useConfigFromGit: true
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  showDivergenceFromBaseBranch: arrowAndNumber
