fork = false
frame = "transparent"
idle = true
maximized = false
neovim-bin = "/opt/homebrew/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
size = 14
hinting = "full"
edging = "subpixelantialias"

[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "W500"

# You can set a different font for fallback
# [[font.normal]]
# family = "Noto Sans CJK SC" 
# style = "Normal"

[[font.bold]]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# No need to specify fallback in every variant, if omitted or specified here
# but not found, it will fallback to normal font with this weight which is bold
# in this case.
# [[font.bold]] 
# family = "Noto Sans CJK SC"
# style = "Bold"
